### ISSUE TITLE
The Index.html is not linked 

### ISSUE THREAD

**Issue by Sarthak-Sidhant** [Sarthak-Sidhant/panel#11]
The index.html must have a linkage to other webpages, it currently does not do that.

**Comment by kauercurtis** [comment]
Check out my pull request. Put hyperlinks in the anchor tags for each list item in the task list except for the calculator (doesn't exist) and the fitness calculator doesnt have a valid html target.

**Comment by Sarthak-Sidhant** [comment]
Yep! Your Pull Request diminishes this Issue, Thanks @kauercurtis
